#!/usr/bin/env python3
"""Regenerate the site's breadcrumbs, sitemap and robots.txt from the pages.

    python3 tools/build-seo.py            # rewrite
    python3 tools/build-seo.py --check    # fail if anything is stale (CI)

Everything here is derived from the HTML itself, so adding a page is enough:
its canonical gives the URL, its <h1> gives the label, and its `meta robots`
decides whether it is indexed at all.

Three outputs:

  * a visible <nav class="breadcrumb"> above each inner page's <h1>, plus the
    matching BreadcrumbList JSON-LD in the same document — Google wants the
    markup to mirror a trail the visitor can actually see;
  * sitemap.xml, covering every indexable page, with <lastmod> taken from the
    file's last commit;
  * robots.txt, with the crawler allow-list and the sitemap pointer.

The generated blocks are fenced by BREADCRUMB markers, so hand-written page
content around them is never touched.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORIGIN = "https://scottymassa.com"

BEGIN = "<!-- BREADCRUMB:begin (generated by tools/build-seo.py) -->"
END = "<!-- BREADCRUMB:end -->"

# Trail label per top-level page. A page absent from here falls back to its
# <h1>, which is usually a headline rather than a label — so prefer an entry.
LABELS = {
    "about.html": "About",
    "aftercare.html": "Aftercare",
    "booking.html": "Booking",
    "contact.html": "Contact",
    "course.html": "Course",
    "geometric-tattoos.html": "Geometric Tattoos",
    "journal.html": "Journal",
    "portfolio.html": "Portfolio",
    "privacy.html": "Privacy",
    "reviews.html": "Reviews",
}

# Crawl priority / cadence. Anything unlisted gets the default.
WEIGHT = {
    "": (1.0, "weekly"),
    "portfolio.html": (0.9, "weekly"),
    "geometric-tattoos.html": (0.9, "monthly"),
    "course.html": (0.9, "monthly"),
    "booking.html": (0.9, "monthly"),
    "reviews.html": (0.8, "monthly"),
    "journal.html": (0.8, "weekly"),
    "about.html": (0.7, "monthly"),
    "contact.html": (0.7, "monthly"),
    "aftercare.html": (0.7, "monthly"),
    "privacy.html": (0.3, "yearly"),
}
DEFAULT_WEIGHT = (0.6, "monthly")

AI_CRAWLERS = [
    "GPTBot", "OAI-SearchBot", "ChatGPT-User", "Google-Extended",
    "PerplexityBot", "ClaudeBot", "Claude-Web", "anthropic-ai",
    "CCBot", "Applebot-Extended", "Bingbot", "Amazonbot", "Meta-ExternalAgent",
]


def pages() -> list[Path]:
    return sorted(ROOT.glob("*.html")) + sorted(ROOT.glob("journal/*.html"))


def rel(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


def text_of(match: re.Match | None) -> str:
    if not match:
        return ""
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", match.group(1))).strip()


class Page:
    def __init__(self, path: Path):
        self.path = path
        self.rel = rel(path)
        self.src = path.read_text(encoding="utf-8")
        self.noindex = bool(re.search(r'<meta[^>]+name="robots"[^>]+noindex', self.src))
        m = re.search(r'<link rel="canonical" href="([^"]+)"', self.src)
        self.canonical = m.group(1) if m else f"{ORIGIN}/{self.rel}"
        self.h1 = text_of(re.search(r"<h1[^>]*>(.*?)</h1>", self.src, re.S))
        self.is_article = self.rel.startswith("journal/")

    @property
    def is_home(self) -> bool:
        return self.rel == "index.html"

    @property
    def loc(self) -> str:
        # The home page is canonically the bare origin, not /index.html.
        return f"{ORIGIN}/" if self.is_home else f"{ORIGIN}/{self.rel}"

    @property
    def label(self) -> str:
        if self.rel in LABELS:
            return LABELS[self.rel]
        # An article keeps the short label already curated in its JSON-LD.
        for m in re.finditer(r'<script type="application/ld\+json">(.*?)</script>', self.src, re.S):
            try:
                data = json.loads(m.group(1))
            except json.JSONDecodeError:
                continue
            pool = data.get("@graph", [data]) if isinstance(data, dict) else data
            for node in pool:
                if isinstance(node, dict) and node.get("@type") == "BreadcrumbList":
                    items = node.get("itemListElement", [])
                    if items:
                        return html.unescape(items[-1]["name"])
        return html.unescape(self.h1)

    @property
    def trail(self) -> list[tuple[str, str]]:
        """(label, url) pairs, root first, current page last."""
        crumbs = [("Home", f"{ORIGIN}/")]
        if self.is_article:
            crumbs.append(("Journal", f"{ORIGIN}/journal.html"))
        crumbs.append((self.label, self.loc))
        return crumbs

    def lastmod(self) -> str:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", self.rel],
            cwd=ROOT, capture_output=True, text=True,
        ).stdout.strip()
        return out or date.today().isoformat()


def breadcrumb_block(page: Page) -> str:
    """The visible trail plus the JSON-LD that mirrors it, as one fenced block."""
    up = "../" if page.is_article else ""
    items = []
    for i, (label, url) in enumerate(page.trail):
        esc = html.escape(label)
        if i == len(page.trail) - 1:
            items.append(f'<li><span aria-current="page">{esc}</span></li>')
        else:
            href = f"{up}index.html" if url == f"{ORIGIN}/" else url.replace(f"{ORIGIN}/", up)
            items.append(f'<li><a href="{href}">{esc}</a></li>')

    ld = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": label, "item": url}
            for i, (label, url) in enumerate(page.trail)
        ],
    }
    ld_text = json.dumps(ld, indent=2, ensure_ascii=False)
    ld_text = "\n".join("      " + line for line in ld_text.splitlines()).lstrip()

    crumbs = "\n          ".join(items)
    return (
        f"{BEGIN}\n"
        f'      <nav class="breadcrumb" aria-label="Breadcrumb">\n'
        f"        <ol>\n"
        f"          {crumbs}\n"
        f"        </ol>\n"
        f"      </nav>\n"
        f'      <script type="application/ld+json">\n'
        f"      {ld_text}\n"
        f"      </script>\n"
        f"      {END}"
    )


def strip_legacy_breadcrumbs(src: str) -> str:
    """Drop the hand-rolled, inline-styled trails the generator replaces."""
    src = re.sub(
        r'\n?\s*<nav aria-label="Breadcrumb"[^>]*>.*?</nav>', "", src, flags=re.S
    )

    def drop_ld(m: re.Match) -> str:
        try:
            data = json.loads(m.group(1))
        except json.JSONDecodeError:
            return m.group(0)
        if isinstance(data, dict) and data.get("@type") == "BreadcrumbList":
            return ""
        if isinstance(data, dict) and "@graph" in data:
            graph = [n for n in data["@graph"] if n.get("@type") != "BreadcrumbList"]
            if len(graph) != len(data["@graph"]):
                data["@graph"] = graph
                body = json.dumps(data, indent=2, ensure_ascii=False)
                body = "\n".join("  " + l for l in body.splitlines())
                return f'<script type="application/ld+json">\n{body}\n  </script>'
        return m.group(0)

    src = re.sub(
        r'<script type="application/ld\+json">\s*(\{.*?\})\s*</script>',
        drop_ld, src, flags=re.S,
    )
    return re.sub(r"\n{3,}", "\n\n", src)


def apply_breadcrumbs(page: Page) -> str:
    if page.is_home or page.noindex:
        return page.src

    src = page.src
    block = breadcrumb_block(page)

    if BEGIN in src:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, src, flags=re.S)

    src = strip_legacy_breadcrumbs(src)

    # Sits inside .page-header, directly above the <h1>.
    m = re.search(r'(<section class="page-header"[^>]*>.*?)(\n\s*<h1)', src, re.S)
    if not m:
        print(f"  !! {page.rel}: no .page-header to host a breadcrumb", file=sys.stderr)
        return src
    return src[: m.end(1)] + "\n      " + block + src[m.end(1):]


def build_sitemap(indexable: list[Page]) -> str:
    rows = []
    for p in sorted(indexable, key=lambda p: (not p.is_home, p.rel)):
        key = "" if p.is_home else p.rel
        priority, freq = WEIGHT.get(key, DEFAULT_WEIGHT)
        rows.append(
            "  <url>\n"
            f"    <loc>{p.loc}</loc>\n"
            f"    <lastmod>{p.lastmod()}</lastmod>\n"
            f"    <changefreq>{freq}</changefreq>\n"
            f"    <priority>{priority}</priority>\n"
            "  </url>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by tools/build-seo.py — do not edit by hand. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(rows)
        + "\n</urlset>\n"
    )


def build_robots(noindex: list[Page]) -> str:
    lines = [
        "# Generated by tools/build-seo.py — do not edit by hand.",
        "",
        "User-agent: *",
        "Allow: /",
        "",
        "# Not landing pages. /partials/ and /assets/ stay crawlable on purpose:",
        "# the header and footer are fetched by JS, and Googlebot has to be able",
        "# to render them.",
        "Disallow: /api/",
        "Disallow: /assets/seo/",
        "Disallow: /emails/",
        "Disallow: /massatattoo/",
        "Disallow: /.git/",
        "Disallow: /.well-known/",
        "",
        "# Transactional pages carry a `noindex` meta tag instead of a Disallow:",
        "# a blocked URL is one Googlebot can never fetch, so it would never see",
        "# the noindex and the page could still surface from inbound links.",
    ]
    lines += [f"#   /{p.rel}" for p in sorted(noindex, key=lambda p: p.rel)]
    lines += ["", "# AI / LLM crawlers — explicitly welcome to index and cite."]
    for agent in AI_CRAWLERS:
        lines += ["", f"User-agent: {agent}", "Allow: /"]
    lines += [
        "",
        "# LLM-friendly site summaries",
        f"# {ORIGIN}/llms.txt",
        f"# {ORIGIN}/llms-full.txt",
        "",
        f"Sitemap: {ORIGIN}/sitemap.xml",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if anything would change")
    args = ap.parse_args()

    all_pages = [Page(p) for p in pages()]
    indexable = [p for p in all_pages if not p.noindex]
    noindex = [p for p in all_pages if p.noindex]

    writes: list[tuple[Path, str]] = []
    for page in all_pages:
        out = apply_breadcrumbs(page)
        if out != page.src:
            writes.append((page.path, out))

    for name, body in (("sitemap.xml", build_sitemap(indexable)),
                       ("robots.txt", build_robots(noindex))):
        path = ROOT / name
        if not path.exists() or path.read_text(encoding="utf-8") != body:
            writes.append((path, body))

    if args.check:
        for path, _ in writes:
            print(f"  stale: {rel(path)}")
        print("stale files:" if writes else "everything up to date", len(writes) or "")
        return 1 if writes else 0

    for path, body in writes:
        path.write_text(body, encoding="utf-8")
        print(f"  wrote {rel(path)}")

    print(f"\n{len(indexable)} indexable pages, {len(noindex)} noindex, {len(writes)} files written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
